language: bash

env:
  - DOCKER_IMAGE=daixijun1990/ansible ANSIBLE_VERSION=2.7.9

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin

script:
  - docker build --build-arg ansible_version=$ANSIBLE_VERSION --tag $DOCKER_IMAGE:v$ANSIBLE_VERSION .
  - docker push $DOCKER_IMAGE:v$ANSIBLE_VERSION
